# Static analysis configuration for Dart & Flutter
# Run `flutter analyze` to check your code.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated/**
    - lib/**/*.g.dart   # Exclude generated files

linter:
  rules:
    # --- Style & formatting ---
    prefer_single_quotes: true       # Use 'single quotes' consistently
    prefer_const_constructors: true  # Encourage using const when possible
    prefer_const_literals_to_create_immutables: true
    sort_child_properties_last: true # Sort widget children last for readability

    # --- Code safety ---
    always_use_package_imports: true # Avoid relative imports across lib/
    avoid_print: true                # Use debugPrint/logging instead
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    avoid_unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true

    # --- Performance ---
    use_decorated_box: true
    use_colored_box: true
    use_super_parameters: true       # Use super.parameter in constructors

    # --- Naming conventions ---
    camel_case_extensions: true
    library_names: true
    file_names: true

# Docs: https://dart.dev/guides/language/analysis-options
