workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      flutter: stable
      java: 17
      vars:
        PACKAGE_NAME: "com.example.gameforge"

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Analyze project
        script: flutter analyze

      - name: Run tests
        script: flutter test

      - name: Build release APK
        script: flutter build apk --release

      - name: Build release AAB
        script: flutter build appbundle --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      email:
        recipients:
          - your@email.com
